### ISSUE TITLE
Cannot stop keg-components

### ISSUE THREAD

**Issue by mpcarolin** [simpleviewinc/keg-cli#8]
With the keg-components container up and running, if I try to stop the container using the command
```bash
keg components stop
```
it does not stop the container and only prints out a function string:

![image](https://user-images.githubusercontent.com/9517356/87361456-2004ce80-c521-11ea-8828-90d237690757.png)

The only way I could stop it was by using the manual command: `docker container stop <id>`

**Comment by mpcarolin** [comment]
This will be fixed once keg-components branch VIS-976-added-injected-apps gets merged into master

**Comment by lancetipton** [comment]
Closing - Fixed via #10
